#!/bin/bash

configfile=$XDG_CONFIG_HOME/xbacklight-ctl/rc.cfg
[ -z ${XDG_CONFIG_HOME+x} ] && configfile=$HOME/.config/xbacklight-ctl/rc.cfg; 

make_config () {
	mkdir -p "${configfile%/*}" 
	printf "PERC=10\\nMAX=100\\nMIN=10\\nNOTIFY=yes\n" > $configfile
}

[ -f $configfile ] || make_config

configfile_secured=/tmp/xbacklight-ctl.cfg

# check if the file contains something we don't want
if egrep -q -v '^#|^[^ ]*=[^;]*' "$configfile"; then
  echo "You can only set variables in your rc.cfg" >&2
  # filter the original to a new file
  egrep '^#|^[^ ]*=[^;&]*'  "$configfile" > "$configfile_secured"
  configfile="$configfile_secured"
fi

source $configfile

quick_notification () {
	[ $NOTIFY = "yes" ] && notify-send "$1" "<b>$2</b>" -u normal -t 500 -i $3 -a xbacklight-ctl --hint=int:transient:1
}

backlight_up () {
	[ -z $PERC ] && PERC=10
	[ -z $MAX ] && MAX=100
	[ $MAX -gt 100 ] && MAX=100
	[ -z $NOTIFY ] && NOTIFY=yes
	local CURR_PERC=`xbacklight | sed "s/\..*//g"`
	[ $(($CURR_PERC+$PERC)) -gt $MAX ] && local PERC=$(($MAX-$CURR_PERC))

	local NEW_PERC=$(($CURR_PERC+$PERC))
	xbacklight -inc $PERC 
	quick_notification "Backlight up $PERC%" "$NEW_PERC%" weather-clear
}

backlight_down () {
	[ -z $PERC ] && PERC=10
	[ -z $MIN ] && MIN=10
	[ $MIN -lt 0 ] && MIN=0
	[ -z $NOTIFY ] && NOTIFY=yes
	local CURR_PERC=`xbacklight | sed "s/\..*//g"`

	[ $(($CURR_PERC-$PERC)) -lt $MIN ] && local PERC=$(($CURR_PERC-$MIN))
	local NEW_PERC=$(($CURR_PERC-$PERC))
	xbacklight -dec $PERC 
	quick_notification "Backlight down $PERC%" "$NEW_PERC%" weather-clear-night
}

backlight_max () {
	xbacklight -set $MAX
	quick_notification "Backlight set to max" "" weather-clear
}


usage () {
	echo "Usage: xbacklight-ctl <up|down|max|help|-h|--help>"
	echo "Config location: $configfile"
}

case "$1" in
	up) backlight_up;;
	down) backlight_down;;
	max) backlight_max;;
	help|-h|--help)
		usage
		exit
	;;
	*) 
		usage 
		exit 1
	;;
esac
